### ISSUE TITLE
 redmine_reddrop was not found

### ISSUE THREAD

**Issue by sudharshanan** [alrick/reddrop#13]
Hi 
  I am trying to install reddrop on my redmine server but showing mentioned below 

**Plugin  redmine_reddrop was not found**

Please help me fixing this issue

**Comment by alrick** [comment]
Hey,

Thanks for your issue.
I'm not working on redmine anymore, it will stay available for the earlier versions.

Feel free to do a pull request if you want to update the plugin for new versions.
